# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aca < Formula
  desc "Advanced Commerce API CLI"
  homepage "https://github.com/dl-alexandre/Advance-Commerce-CLI"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.3/aca_0.0.3_darwin_x86_64.tar.gz"
      sha256 "3e23ae638bfa8c49061d0b1e70398ea11f2b449c63b302fc774ec5859aa53c5a"

      define_method(:install) do
        bin.install "aca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.3/aca_0.0.3_darwin_arm64.tar.gz"
      sha256 "b697fa0d8329966588e4a7d385e242a935250f413828d61e352ad828209908a1"

      define_method(:install) do
        bin.install "aca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.3/aca_0.0.3_linux_x86_64.tar.gz"
      sha256 "4c6a49ce71facdf89549bd5231a3225dd11964e6f99877edb60683b370abd179"
      define_method(:install) do
        bin.install "aca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.3/aca_0.0.3_linux_arm64.tar.gz"
      sha256 "2ff1a0e2178ce9bd7bf92597808e689f9cb1ab3839d0b12faa5fd4e236671e5f"
      define_method(:install) do
        bin.install "aca"
      end
    end
  end

  test do
    system "#{bin}/aca", "--help"
  end
end
