# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aca < Formula
  desc "Advanced Commerce API CLI"
  homepage "https://github.com/dl-alexandre/Advance-Commerce-CLI"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.4/aca_0.0.4_darwin_x86_64.tar.gz"
      sha256 "9ad01aee5e35b3b73c917f891c234bc34b2bee09f135e830379f4a03cdf3a9f5"

      define_method(:install) do
        bin.install "aca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.4/aca_0.0.4_darwin_arm64.tar.gz"
      sha256 "656561bc93823f4f0df75a77e89ea90a7325c4dfdcb4932c17dd80297eb4c362"

      define_method(:install) do
        bin.install "aca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.4/aca_0.0.4_linux_x86_64.tar.gz"
      sha256 "423a03baa21cef18693e2f908e09e5fe4f3c31a7b8335d71322f0d51f8187c3f"
      define_method(:install) do
        bin.install "aca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Advance-Commerce-CLI/releases/download/v0.0.4/aca_0.0.4_linux_arm64.tar.gz"
      sha256 "c52f26eb7ceb18936e75c4980d24d2b2286587367ee6bffd2bc336f0d7792af9"
      define_method(:install) do
        bin.install "aca"
      end
    end
  end

  test do
    system "#{bin}/aca", "--help"
  end
end
