# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ams < Formula
  desc "Apple Map Server CLI"
  homepage "https://github.com/dl-alexandre/Apple-Map-Server-CLI"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.10/ams-darwin-amd64.tar.gz"
      sha256 "f836334e829b0b98f785b1ce6b2d3c13d1b1d4682474f5d881c60c69b897d6f3"

      define_method(:install) do
        bin.install "ams"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.10/ams-darwin-arm64.tar.gz"
      sha256 "2e4fa1764e763e84db25cbf379ae92fab308d171154fef0ba5dd49b508342b95"

      define_method(:install) do
        bin.install "ams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.10/ams-linux-amd64.tar.gz"
      sha256 "f5d846b717b150bb1e14b3a240e826a414887b4bd3bc5a4930c070798d9bbffd"
      define_method(:install) do
        bin.install "ams"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.10/ams-linux-arm64.tar.gz"
      sha256 "e18f3fc3b979d75d7ce31851aa5c58903be0fc132414fa8093f9689afe241328"
      define_method(:install) do
        bin.install "ams"
      end
    end
  end

  test do
    system "#{bin}/ams", "version"
  end
end
