# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ams < Formula
  desc "Apple Map Server CLI"
  homepage "https://github.com/dl-alexandre/Apple-Map-Server-CLI"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.11/ams-darwin-amd64.tar.gz"
      sha256 "8988f95f651f4234720eadb8e41059e2dd12ca09eea88186688c48e4da7da167"

      define_method(:install) do
        bin.install "ams"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.11/ams-darwin-arm64.tar.gz"
      sha256 "d8b58b49d4cb7245e1848a973ba0ea507cf3f5ee36c05dac02ac4f23874bcd9f"

      define_method(:install) do
        bin.install "ams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.11/ams-linux-amd64.tar.gz"
      sha256 "0343a8b54e5132bfaf7c4d20993b8af0b2995fae294a3920298da0936c43d36c"
      define_method(:install) do
        bin.install "ams"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Map-Server-CLI/releases/download/v0.0.11/ams-linux-arm64.tar.gz"
      sha256 "03db21c2c4e4a85a4b4d11eaabdbb43519168ceec921ad2c970259118a207e72"
      define_method(:install) do
        bin.install "ams"
      end
    end
  end

  test do
    system "#{bin}/ams", "version"
  end
end
