# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cimis < Formula
  desc "CLI for California Irrigation Management Information System (CIMIS) weather data"
  homepage "https://github.com/dl-alexandre/cimis-cli"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/cimis-cli/releases/download/v0.0.9/cimis-darwin-amd64.tar.gz"
      sha256 "737ba4520517f539c2f8d711bc73fba51b1ed8d188a528ea1e3cf799cf4f36b8"

      define_method(:install) do
        bin.install "cimis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/cimis-cli/releases/download/v0.0.9/cimis-darwin-arm64.tar.gz"
      sha256 "d47db8370fd00bfe406990ffc6e75f6b66870c92b14bcb749562fc83ab877dc2"

      define_method(:install) do
        bin.install "cimis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cimis-cli/releases/download/v0.0.9/cimis-linux-amd64.tar.gz"
      sha256 "526d1ce9227f555f28ea4c36f4413f8000288ddbecd6e48e24d53446178b6a15"
      define_method(:install) do
        bin.install "cimis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cimis-cli/releases/download/v0.0.9/cimis-linux-arm64.tar.gz"
      sha256 "aea2df8490d2be6e1c9b05dc08af065544b2595571e2ee897ed70bf4095a3acc"
      define_method(:install) do
        bin.install "cimis"
      end
    end
  end

  test do
    system "#{bin}/cimis", "version"
  end
end
