# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdrv < Formula
  desc "Fast, lightweight CLI for Google Drive"
  homepage "https://github.com/dl-alexandre/Google-Drive-CLI"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.2/gdrv-darwin-amd64.tar.gz"
      sha256 "9a21d10bf1d3b2f48b1a98df916fd4db33f85be0ee79b5c0a1f3691b5d9735ce"

      define_method(:install) do
        bin.install "gdrv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.2/gdrv-darwin-arm64.tar.gz"
      sha256 "b913ce6421e0041481313c0c772070dca96926ff192ceaadbb142ddccf8e34a8"

      define_method(:install) do
        bin.install "gdrv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.2/gdrv-linux-amd64.tar.gz"
      sha256 "8fdc8a8887545ae477796e7fcbe8095f09d16eb7de4ea8a69ca873d996d2ef34"
      define_method(:install) do
        bin.install "gdrv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.2/gdrv-linux-arm64.tar.gz"
      sha256 "3eae3af36927351da6607c8b37e7d5c0851b85932776c66c831541def6c9a3ed"
      define_method(:install) do
        bin.install "gdrv"
      end
    end
  end

  test do
    system "#{bin}/gdrv", "version"
  end
end
