# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpd < Formula
  desc "Fast, lightweight CLI for Google Play Console"
  homepage "https://github.com/dl-alexandre/Google-Play-Developer-CLI"
  version "0.5.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.5.9/gpd-darwin-amd64.tar.gz"
      sha256 "080c68707bd9fa7b325235174b9f85bafe2cd3057dc6baf0508a927dcc1d349b"

      define_method(:install) do
        bin.install "gpd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.5.9/gpd-darwin-arm64.tar.gz"
      sha256 "0d2676025959d892e0a26311acde4cc43be63d06b0404f8996cbc6ea590650d0"

      define_method(:install) do
        bin.install "gpd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.5.9/gpd-linux-amd64.tar.gz"
      sha256 "af1490f35c31410ac9d6c3533fdf818ffce950bdeca0d90502483c32d876d870"
      define_method(:install) do
        bin.install "gpd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.5.9/gpd-linux-arm64.tar.gz"
      sha256 "a47e88cab7c2f535713976e0d3c2165f8de0120dc3fcbd340d4121582808f5fc"
      define_method(:install) do
        bin.install "gpd"
      end
    end
  end

  test do
    system "#{bin}/gpd", "version"
  end
end
