# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grokipedia < Formula
  desc "Grokipedia CLI - command-line interface for the Grokipedia API"
  homepage "https://github.com/dl-alexandre/Grokipedia-CLI"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.3/grokipedia_0.0.3_darwin_x86_64.tar.gz"
      sha256 "556b5c42d016cd16c27cbf2e9af9a0d3202148fe1d47db566e4aea851818cfa8"

      define_method(:install) do
        bin.install "grokipedia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.3/grokipedia_0.0.3_darwin_arm64.tar.gz"
      sha256 "d811413ba1daf7ac53e35c4aaad3cff3372da8cac3e9bc2c02f11fdd1c565238"

      define_method(:install) do
        bin.install "grokipedia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.3/grokipedia_0.0.3_linux_x86_64.tar.gz"
      sha256 "c8b68ef3e0afaf9e460d52ad3700b684f151388e15b91091366e18c757860333"
      define_method(:install) do
        bin.install "grokipedia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.3/grokipedia_0.0.3_linux_arm64.tar.gz"
      sha256 "f58766ba6af591f530c29a9511960eef87c28a647cbf9f5e870d9c76a45f448b"
      define_method(:install) do
        bin.install "grokipedia"
      end
    end
  end

  test do
    system "#{bin}/grokipedia", "--help"
  end
end
