# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpr < Formula
  desc "CLI for USDA AMS MyMarketNews Datamart API"
  homepage "https://github.com/dl-alexandre/MyMarketNews-CLI"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.6/mpr-darwin-amd64.tar.gz"
      sha256 "84bb21f801bf3389f9db4cfbd1fca1c3a73f563141484498af36b034682da6ea"

      define_method(:install) do
        bin.install "mpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.6/mpr-darwin-arm64.tar.gz"
      sha256 "3929800b2de921009b0c47ca215a66f22d6f59360d24196571690b3b2b2aad23"

      define_method(:install) do
        bin.install "mpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.6/mpr-linux-amd64.tar.gz"
      sha256 "6286188fa5e75a59d3efbeead45b25c317ccd8b6f95659414f5e7192fed61888"
      define_method(:install) do
        bin.install "mpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.6/mpr-linux-arm64.tar.gz"
      sha256 "b3112ab757edaa82bc083921fe504ace857098a796ce57fdd768e70e875feae9"
      define_method(:install) do
        bin.install "mpr"
      end
    end
  end

  test do
    system "#{bin}/mpr", "version"
  end
end
