# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpr < Formula
  desc "CLI for USDA AMS MyMarketNews Datamart API"
  homepage "https://github.com/dl-alexandre/MyMarketNews-CLI"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.5/mpr-darwin-amd64.tar.gz"
      sha256 "5cfbddd681f42e6e55cdfc8544d8588e8bd8064010723b5cb234b6c046958805"

      define_method(:install) do
        bin.install "mpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.5/mpr-darwin-arm64.tar.gz"
      sha256 "34eb163a64562b8493f9c80f8e577f6af6187a1dd36d4d09726b0ec35a7f3e4d"

      define_method(:install) do
        bin.install "mpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.5/mpr-linux-amd64.tar.gz"
      sha256 "c12d1c166de082bcd08c090df9f9b6a71f0a59da4b419394f99b7a0f165e092a"
      define_method(:install) do
        bin.install "mpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.5/mpr-linux-arm64.tar.gz"
      sha256 "b4ade812f0d925e785963c6ddce7887fe10124497910c327091c79b1c09c755e"
      define_method(:install) do
        bin.install "mpr"
      end
    end
  end

  test do
    system "#{bin}/mpr", "version"
  end
end
