# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unifi < Formula
  desc "CLI for local UniFi controller management"
  homepage "https://github.com/dl-alexandre/Local-UniFi-CLI"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.9/unifi-darwin-amd64.tar.gz"
      sha256 "458a3ce2d532f7d21589b9fcd0a308504b85d1cc84fababcb9600d830a686249"

      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.9/unifi-darwin-arm64.tar.gz"
      sha256 "dc9f7c847b6079b50441c0965fc5384617f2fa186d0b009d396d5f9452321a26"

      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.9/unifi-linux-amd64.tar.gz"
      sha256 "ae677e95ab3edcdfe9231fe322e1787f35b09062c66b7e619df3ceeaf161a583"
      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.9/unifi-linux-arm64.tar.gz"
      sha256 "42437f90851181f938e6f0072caf0f6ec65532da65bfb0016bbe3d6658d9691f"
      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  test do
    system "#{bin}/unifi", "version"
  end
end
