# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unifi < Formula
  desc "CLI for local UniFi controller management"
  homepage "https://github.com/dl-alexandre/Local-UniFi-CLI"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.5/unifi-darwin-amd64.tar.gz"
      sha256 "5bbc7c0d113fe115c0a71ccc7e62f2e790959ad5a4148b3efca7e5aabe1dab98"

      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.5/unifi-darwin-arm64.tar.gz"
      sha256 "45ff57152fafb843ac3439167491197c3c59ee32f6358f3f92f100064e6b865a"

      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.5/unifi-linux-amd64.tar.gz"
      sha256 "99d87ce96d6a8eaf9c11ed8a720ff74e8b0ca2c896bfe03a435742c8e1604a5b"
      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.5/unifi-linux-arm64.tar.gz"
      sha256 "f7bf2cf4523d0e55365778563d85ea80b2d4da349f14583d9df09142bfe31700"
      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  test do
    system "#{bin}/unifi", "version"
  end
end
