# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usm < Formula
  desc "Full-featured CLI for managing UniFi networks via Site Manager API"
  homepage "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-darwin-amd64.tar.gz"
      sha256 "25b5f5992b424e04306ac11e2d4769684e6c058fd2252b55da70460bc28e082a"

      define_method(:install) do
        bin.install "usm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-darwin-arm64.tar.gz"
      sha256 "458380a26c68ec47588520b12730a0e9f8ec5da0cd6b3d10e9145cab87c0510b"

      define_method(:install) do
        bin.install "usm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-linux-amd64.tar.gz"
      sha256 "e4c88c7932cbfdf4ca2ee96c68868bbde21fa62338f05e2ff564be8c50579977"
      define_method(:install) do
        bin.install "usm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-linux-arm64.tar.gz"
      sha256 "2a5b368196d15a9aac0e390ab68b80c80a82774c9c71935a3d9af2cae008e8c3"
      define_method(:install) do
        bin.install "usm"
      end
    end
  end

  test do
    system "#{bin}/usm", "version"
  end
end
