# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X < Formula
  desc "X CLI"
  homepage "https://github.com/dl-alexandre/X-CLI"
  version "v0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.4/x_Darwin_x86_64.tar.gz"
      sha256 "02ec1a680eea6ae8ec4610f826e28d252123c104fe9fc46240cc654322a630fa"

      def install
        bin.install "x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.4/x_Darwin_arm64.tar.gz"
      sha256 "3cc2c2529b43f3b12df909227d2ae362f57d0c3129248f385158ac3208e53041"

      def install
        bin.install "x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.4/x_Linux_x86_64.tar.gz"
      sha256 "d4bd350eabf00a413766e8e3ee600284f1f2125f816354996976ae29fad7d51e"
      def install
        bin.install "x"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.4/x_Linux_arm64.tar.gz"
      sha256 "4f03fab758adf3137ae861cb82c079f6cd06dc9bd7ffe28c7380538b2a2417eb"
      def install
        bin.install "x"
      end
    end
  end

  test do
    system "#{bin}/x", "version"
  end
end
